### ISSUE TITLE
v1.6.1 Feature List

### ISSUE THREAD

**Issue by caesar0301** [caesar0301/treelib#128]
v1.6.1 Feature List:
* [x] Support subtrees with inter-node pointers  (#127)
* [x] Support composite (derived) tree class
* [x] Replace long if-else blocks with look-up tables (#109)
* [x] Shallow pastes to multiple trees breaks level/depth (#88 #131 )
* [x] Ability to paste trees at root level (#87 #134 )
* [x] Fix removal of root node (#119 #130)
* [x] Tree merge feature (#138)
* [x] Optional print in show method (#139)

**Comment by caesar0301** [comment]
Welcome to join me on branch `dev`

**Comment by leonardbinet** [comment]
I'm not sure to get it, looking at `dev` branch commits I find no trace of my previous commits, did you remove them?

**Comment by leonardbinet** [comment]
Ah I guess you squashed commits

**Comment by caesar0301** [comment]
@leonardbinet Yes, I squashed and reviewed the patch last weekend. Your `*_in_tree` functions are replaces by new predecessor and successors interfaces, which deprecate previous `bpointer` and `fpointer`. An optional arg `tree_id` is appended to functions such as `is_leaf` and `is_root` without proposing new interfaces.

TODO: before we finish #123:
1. make `tree_id` as optional arg in setter and getter of predecessor & successors. #123 is an enhanced feature of logic subtrees. It should not effect the clearness of existing interfaces for some simple use cases.
2. more UTs to cover the potential errors after introducing this tree-wise feature.

**Comment by leonardbinet** [comment]
@caesar0301 well done for the implementation, I agree with you it is more elegant this way 👍 

However why was it necessary for you to squash commits? If you want me to squash my commits in a single one to avoid having too many, no problem I understand  🙂. But the problem here is that you totally deleted my contribution from the history of the repository (as detailed here: https://github.com/isaacs/github/issues/1303). 

This quite matters to me, since I see contributions to open-source projects are the main way for me to showcase my capabilities to potential recruitors etc. In this case I won't appear in git blame, history, or contributors of the repo, whereas I spend quite an effort trying to make a meaningful contribution. 
Would you consider restoring the history?

**Comment by leonardbinet** [comment]
Actually, I could restore history without requiring the `feature/tree-wise-node-pointer` branch. I simply squashed my commits and cherry-picked your following ones:
<img width="1046" alt="Capture d’écran 2019-12-15 à 11 50 50" src="https://user-images.githubusercontent.com/1590371/70861650-5c436280-1f31-11ea-8682-758de530ce5c.png">

The `dev2` branch is now at the exact same point than `dev` branch, with only difference being my squashed commit `b8e32fd2e80604c479bc0fdc11c4140cf13c29a3`.

I now only need to force-push `dev2` branch into `dev` branch and we're good to go, is it ok for you?

**Comment by leonardbinet** [comment]
FYI I would rather first solve above situation before merging #130 and #134.

**Comment by leonardbinet** [comment]
FYI to merge #130 and #134 I pushed the branch with restored history in `dev`, and kept a copy of your initial branch `dev`-> `dev_save` so you can compare.

**Comment by leonardbinet** [comment]
@caesar0301 do you want to include serialization/deserialization #85 in this release? or should we release the current state and make another release in which we'll have time to discuss this separate subject?

**Comment by caesar0301** [comment]
@leonardbinet It is fair the remain your efforts on the project. I compare both dev and dev_save branch and that is OK.
I agree with you to start a new release on #85 and #95. Before the release, I should fix the TODOs in https://github.com/caesar0301/treelib/issues/128#issuecomment-564052527 on issue #127.

**Comment by leonardbinet** [comment]
@caesar0301 for the TODO:

>  make `tree_id` as optional arg in setter and getter of predecessor & successors. #127 is an enhanced feature of logic subtrees. It should not effect the clearness of existing interfaces for some simple use cases.

-> I disagree, it is a fix, not an additional feature. If you don't set this `tree_id` we arg you necessarily will have unexpected behaviour while using a `node` in multiple `trees` (using `sub_tree`/`remove_subtree` for instance) methods since a node won't have same predecessor and successors in different `trees`. And I don't think choosing arbitrary the first `tree` in which the node has been placed is a good idea (I've commented this subject on this issue: https://github.com/caesar0301/treelib/issues/121).

>  more UTs to cover the potential errors after introducing this tree-wise feature.

-> IMO it's not that bad but I might help on this, on which methods do you want to increase test coverage?

**Comment by leonardbinet** [comment]
In the library I plan to release I make use of this feature https://github.com/caesar0301/treelib/pull/138, would you agree to merge such feature in this release?

**Comment by caesar0301** [comment]
> > make `tree_id` as optional arg in setter and getter of predecessor & successors. #127 is an enhanced feature of logic subtrees. It should not effect the clearness of existing interfaces for some simple use cases.
> 
> -> I disagree, it is a fix, not an additional feature. If you don't set this `tree_id` argument you will have unexpected behaviour while using a `node` in multiple `trees` (using `sub_tree`/`remove_subtree` for instance) methods since a node won't have same predecessor and successors in different `trees`. And I don't think choosing arbitrary the first `tree` in which the node has been placed is a good idea (I've commented this subject on this issue: #121).

It is reasonable to think about `tree_id` when we are talking about multree features. But it doesn't convince me to accept an implementation mannar that expose inner complexities of software or library to users when they merely need basic features in most cases.

I agree with you that it is a fix. It is better to leave it for future release.

**Comment by caesar0301** [comment]
> In the library I plan to release I make use of this feature #138, would you agree to merge such feature in this release?

It seems a helpful feature and not complicated to do. Let's release 161 when you finish this feature.
