### ISSUE TITLE
Dev Roadmap

### ISSUE THREAD

**Issue by caesar0301** [caesar0301/treelib#153]
## v1.6.2
* [ ] Support tree loader from json/graphviz/dict/yaml (#85)
* [ ] Enhance tree dumping to json/graphviz/dict/yaml (#85)
* [ ] Support output to an arbitrary io-stream (#95)
